# Generated by Django 3.1.3 on 2021-01-15 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pythonlearners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='img',
            field=models.ImageField(default=None, upload_to='static'),
        ),
    ]
