# Generated by Django 3.1.3 on 2021-01-15 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pythonlearners', '0002_members_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='purpose',
            field=models.CharField(max_length=30),
        ),
    ]
